// WAVE-MEASUREMENT
// UA1

// WAVE-MEASUREMENT primary swell
// UG1

// WAVE-MEASUREMENT secondary swell
// UG2

// PLATFORM-ICE-ACCRETION
// WA1

// WATER-SURFACE-ICE-OBSERVATION
// WD1

// WATER-SURFACE-ICE-HISTORICAL-OBSERVATION
// WG1

// WATER-LEVEL-OBSERVATION
// WJ1

// SEA-SURFACE-TEMPERATURE-OBSERVATION
// sa1(x)