export const weather_source = {
    "AU": "sourced from automated ASOS/AWOS sensors",
    "AW": "sourced from automated sensors",
    "MW": "sourced from manually reported present weather"
}
export const weather_type = {
    "01": "Fog, ice fog or freezing fog (may include heavy fog)",
    "02": "Heavy fog or heavy freezing fog (not always distinguished from fog)",
    "03": "Thunder",
    "04": "Ice pellets, sleet, snow pellets or small hail",
    "05": "Hail (may include small hail)",
    "06": "Glaze or rime",
    "07": "Dust, volcanic ash, blowing dust, blowing sand or blowing obstruction",
    "08": "Smoke or haze",
    "09": "Blowing or drifting snow",
    "10": "Tornado, water spout or funnel cloud",
    "11": "High or damaging winds",
    "12": "Blowing spray",
    "13": "Mist",
    "14": "Drizzle",
    "15": "Freezing drizzle",
    "16": "Rain",
    "17": "Freezing rain",
    "18": "Snow, snow pellets, snow grains or ice crystals",
    "19": "Unknown precipitation",
    "21": "Ground fog",
    "22": "Ice fog or freezing fog"
}
export const weather_intensity_code = {
    "0": "Not Reported",
    "1": "Light (-)",
    "2": "Moderate or Not Reported (no entry in original observation)",
    "3": "Heavy (+)",
    "4": "Vicinity (VC)",
    "9": "Missing"
}
export const weather_descriptor_code = {
    "0": "No Descriptor",
    "1": "Shallow (MI)",
    "2": "Partial (PR)",
    "3": "Patches (BC)",
    "4": "Low Drifting (DR)",
    "5": "Blowing (BL)",
    "6": "Shower(s) (SH)",
    "7": "Thunderstorm (TS)",
    "8": "Freezing (FZ)",
    "9": "Missing"
}
export const weather_precipitation_code = {
    "00": "No Precipitation",
    "01": "Drizzle (DZ)",
    "02": "Rain (RA)",
    "03": "Snow (SN)",
    "04": "Snow Grains (SG)",
    "05": "Ice Crystals (IC)",
    "06": "Ice Pellets (PL)",
    "07": "Hail (GR)",
    "08": "Small Hail and/or Snow Pellets (GS)",
    "09": "Unknown Precipitation (UP)",
    "99": "Missing"
}

export const weather_obscuration_code = {
    "0": "No Obscuration",
    "1": "Mist (BR)",
    "2": "Fog (FG)",
    "3": "Smoke (FU)",
    "4": "Volcanic Ash (VA)",
    "5": "Widespread Dust (DU)",
    "6": "Sand (SA)",
    "7": "Haze (HZ)",
    "8": "Spray (PY)",
    "9": "Missing"
}
export const weather_phenomena_code = {
    "0": "None Reported",
    "1": "Well-Developed Dust/Sand Whirls (PO)",
    "2": "Squalls (SQ)",
    "3": "Funnel Cloud, Tornado, Waterspout (FC)",
    "4": "Sandstorm (SS)",
    "5": "Duststorm (DS)",
    "9": "Missing"
}
export const weather_combination_code = {
    "1": "Not part of combined weather elements",
    "2": "Beginning element of combined weather elements",
    "3": "Combined with previous weather element to form a single weather report",
    "9": "Missing"
}

// (Code figures 20-26 are used to report precipitation, fog, thunderstorm at the station during the preceding hour,but not at the time of observation.)
export const weather_atmosphere_automated_condition_code = {
    "00": "No significant weather observed",
    "01": "Clouds generally dissolving or becoming less developed",
    "02": "State of sky on the whole unchanged during the past hour",
    "03": "Clouds generally forming or developing during the past hour",
    "04": "Haze, smoke, or dust in suspension in the air, visibility equal to or greater than 1km",
    "05": "Smoke",
    "07": "Dust or sand raised by wind at or near the station at the time of observation, but no well-developed dust irl(s) whirls(s) or sand whirl(s), and no duststorm or sandstorm seen or, in the case of ships, blowing spray at the station",
    "10": "Mist",
    "11": "Diamond dust",
    "12": "Distant lightning",
    "18": "Squalls",
    "20": "Fog",
    "21": "Precipitation",
    "22": "Drizzle (not freezing) or snow grains",
    "23": "Rain (not freezing)",
    "24": "Snow",
    "25": "Freezing drizzle or freezing rain",
    "26": "Thunderstorm (with or without precipitation)",
    "27": "Blowing or drifting snow or sand",
    "28": "Blowing or drifting snow or sand, visibility equal to or greater than 1 km",
    "29": "Blowing or drifting snow or sand, visibility less than 1 km",
    "30": "Fog",
    "31": "Fog or ice fog in patches",
    "32": "Fog or ice fog, has become thinner during the past hour",
    "33": "Fog or ice fog, no appreciable change during the past hour",
    "34": "Fog or ice fog, has begun or become thicker during the past hour",
    "35": "Fog, depositing rime",
    "40": "Precipitation",
    "41": "Precipitation, slight or moderate",
    "42": "Precipitation, heavy",
    "43": "Liquid precipitation, slight or moderate",
    "44": "Liquid precipitation, heavy",
    "45": "Solid precipitation, slight or moderate",
    "46": "Solid precipitation, heavy",
    "47": "Freezing precipitation, slight or moderate",
    "48": "Freezing precipitation, heavy",
    "50": "Drizzle",
    "51": "Drizzle, not freezing, slight",
    "52": "Drizzle, not freezing, moderate",
    "53": "Drizzle, not freezing, heavy",
    "54": "Drizzle, freezing, slight",
    "55": "Drizzle, freezing, moderate",
    "56": "Drizzle, freezing, heavy",
    "57": "Drizzle and rain, slight",
    "58": "Drizzle and rain, moderate or heavy",
    "60": "Rain",
    "61": "Rain, not freezing, slight",
    "62": "Rain, not freezing, moderate",
    "63": "Rain, not freezing, heavy",
    "64": "Rain, freezing, slight",
    "65": "Rain, freezing, moderate",
    "66": "Rain, freezing, heavy",
    "67": "Rain or drizzle and snow, slight",
    "68": "Rain or drizzle and snow, moderate or heavy",
    "70": "Snow",
    "71": "Snow, slight",
    "72": "Snow, moderate",
    "73": "Snow, heavy",
    "74": "Ice pellets, slight",
    "75": "Ice pellets, moderate",
    "76": "Ice pellets, heavy",
    "77": "Snow grains",
    "78": "Ice crystals",
    "80": "Showers or intermittent precipitation",
    "81": "Rain showers or intermittent rain, slight",
    "82": "Rain showers or intermittent rain, moderate",
    "83": "Rain showers or intermittent rain, heavy",
    "84": "Rain showers or intermittent rain, violent",
    "85": "Snow showers or intermittent snow, slight",
    "86": "Snow showers or intermittent snow, moderate",
    "87": "Snow showers or intermittent snow, heavy",
    "89": "Hail",
    "90": "Thunderstorm",
    "91": "Thunderstorm, slight or moderate, with no precipitation",
    "92": "Thunderstorm, slight or moderate, with rain showers and/or snow showers",
    "93": "Thunderstorm, slight or moderate, with hail",
    "94": "Thunderstorm, heavy, with no precipitation",
    "95": "Thunderstorm, heavy, with rain showers and/or snow",
    "96": "Thunderstorm, heavy, with hail",
    "99": "Tornado"
}


